ALTER TABLE users ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE office_invitation ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE notification ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE favorite_colleague ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE booking ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
